language: java
jdk: oraclejdk8
dist: trusty

before_install:
    - chmod +x gradlew

notifications:

    email:
        - alex08lta@gmail.com
        - juanfernandez@alumnos.unc.edu.ar

script:
    - ./gradlew clean build

git:
    quiet: true
