language: java
jdk: oraclejdk8
dist: trusty

before_install:
    - chmod +x gradlew
    - chmod +x after_script.sh

notifications:

    email:
        - alex08lta@gmail.com
        - juanfernandez@alumnos.unc.edu.ar

before_script:
    - ./gradlew clean build

script:
    - ./after_script.sh

git:
    quiet: true
