language: java
jdk: oraclejdk8

before_install:
    - chmod +x gradlew

notifications:

    email:
        - alex08lta@gmail.com
        - juanfernandez@alumnos.unc.edu.ar
        - aixa.carrizo1704@gmail.com

script:
    - ./gradlew build
